name: Workflow with Email Identifier

on:
  # Trigger manually or on push to main branch
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: 23f3000387@ds.study.iitm.ac.in
        run: echo "Hello from IITM student!"

      - name: Display Date
        run: date
